<!DOCTYPE html>
<html>

<!--HELLO WORLD.PHP-->

<body>

<?php
$txt = "Hello World";
$x = 5;
$y = 10.5;

echo $txt;
echo "<br>";
print $x; #Print takes only one argument, unlike echo
echo "<br>";
var_dump($y.", ");
var_dump($y);

echo "<br>txt = $txt <br>";
echo "txt = " . $txt . "<br>";
?>

<?php
$hw = "Hello world!";
$fn = "Kelly";
$ln = "Mayhew";

echo "<h1>$hw</h1><br>";
echo "<p>My name is: ".$fn." ".$ln."</p>";
?>

<?php
$arr = array("AAAAA",false,13, "[3]=> int(20)");
echo $arr."<br>";
print "$arr<br>";
var_dump($arr);
echo "<br>";
for($i=0; $i < count($arr); $i++){
  echo $arr[$i].", ";
}
echo "<br>counter after loop is $i";
print "<br>";

function enter(){
  echo "<br><br>";
}
enter();
echo "after the function";
enter();
?>

<?php
echo "'$i' is not local?";
enter();

class Animal{
  function animal($x, $y){
    $this->name = $x;
    $this->age = $y;
  }
}

$pet1 = new animal("Quentin", $arr[2]);
$pet2 = new animal("Phil", 4);
var_dump($pet1);
echo "<br>$pet2->name is $pet2->age years old!";
enter();
enter();

function myTest(){
  static $q = 0;
  $q++;
  echo "q in function is $q, ";
  return $q;
}
$p = myTest();
echo "q returned from function is $p, ";
echo "q out of function is $q<br>";
$p = myTest();
echo "<br>done again is $p. It changed!";
?>

<br><br><br>
<h1>Random Numbers!</h1>
<?php
echo "Largest number generated by rand() is: ".getrandmax()."<br />";
echo "Smallest number generated by rand() is: 0<br /><br />";
echo "rand(1,100) - Generate 10 numbers between and including 1 and 100:";
echo "<br />";
for ($i=1; $i<=10; $i++){
    echo rand(1,100).", ";
}
echo "<br /><br />";
echo "rand() - Generate 10 numbers (any from 0 to max value)<br />";
for ($i=1; $i<=10; $i++){
    echo rand()."<br />"; 
}
echo "<br />";
echo "mt_rand() - Better and 4 times faster! Uses Mersenne Twister algorithm";
echo "<br />";
for ($i=1; $i<=10; $i++){
    echo mt_rand()."<br />";
}
enter();

echo "coming from: ".$_SERVER['REMOTE_ADDR'];

enter(); enter(); enter();
?>


<?php
echo $_SERVER['PHP_SELF']." [where is this file]";
echo "<br>"; echo $_SERVER['SERVER_NAME']. " [name of server]";
echo "<br>"; echo $_SERVER['HTTP_HOST']. " [hosted by]";
echo "<br>"; echo $_SERVER['HTTP_REFERER']." [complete url of current page (sometimes)]";
echo "<br>"; echo $_SERVER['HTTP_USER_AGENT']." [Header info]";
echo "<br>"; echo $_SERVER['SCRIPT_NAME']." [path of the script]";
echo "<br>"; echo "<br>";
echo "Other interesting elements:";
echo "<br>"; echo $_SERVER['SERVER_ADDR']." [returns the IP address of host server]";
echo "<br>"; echo $_SERVER['REMOTE_ADDR']." [IP address of the user]";
echo "<br>"; echo "<br>"; 
echo "<a href='http://php.net/manual/en/reserved.variables.server.php'>       
More about SERVER elements found here</a>";
?>


</body>
</html>